export const V2ClientChannels = {
  enabled: "blast:v2:enabled",
  subscribe: "blast:v2:subscribe",
  unsubscribe: "blast:v2:unsubscribe",
  snapshot: "blast:v2:snapshot",
  toast: "blast:v2:toast",
  start: "blast:v2:start",
  refreshCommands: "blast:v2:refresh-commands",
  runCommand: "blast:v2:run-command",
  stopCommand: "blast:v2:stop-command",
  sceneEvent: "blast:v2:scene-event",
  close: "blast:v2:close",
  extensionPackagesEnabled: "blast:v2:extension-packages-enabled",
  installExtensionPackage: "blast:v2:install-extension-package",
  updateExtensionPackage: "blast:v2:update-extension-package",
  removeExtensionPackage: "blast:v2:remove-extension-package",
  rollbackExtensionPackage: "blast:v2:rollback-extension-package",
} as const;
