name: Publish

on:
  push:
    branches: ["main"]
    paths:
      - ".github/**"
      - ".nvmrc"
      - ".oxfmt*"
      - ".oxlint*"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - "packages/**"
      - "apps/**"

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    name: Build and Publish (${{ matrix.os }} - ${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x64
          - os: macos-15-intel
            arch: x64
          - os: macos-15
            arch: arm64

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: ./.github/actions/setup-repo

      - name: Build
        run: pnpm run build

      - name: Run Tests
        run: pnpm run test

      - name: Run Lint
        run: pnpm run lint

      - name: Check Formatting
        run: pnpm run fmt:check

      # - name: Set MacOS signing certs
      #   if: matrix.os == 'macOS-latest'
      #   run: chmod +x tools/add-macos-cert.sh && ./tools/add-macos-cert.sh
      #   env:
      #     MACOS_CERT_P12: ${{ secrets.MACOS_CERT_P12 }}
      #     MACOS_CERT_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}

      - run: pnpm run publish --arch=${{ matrix.arch }}
        working-directory: ./apps/electron-client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CSC_NAME: ${{ secrets.CSC_NAME }}
