name: Publish

on:
  push:
    branches: ["main"]

jobs:
  publish:
    name: Build and Publish (${{ matrix.os }} - ${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        # Build for supported platforms
        # https://github.com/electron/electron-packager/blob/ebcbd439ff3e0f6f92fa880ff28a8670a9bcf2ab/src/targets.js#L9
        # 32-bit Linux unsupported as of 2019: https://www.electronjs.org/blog/linux-32bit-support
        os: [ macOS-latest, ubuntu-latest, windows-latest ]
        arch: [ x64, arm64 ]
        include:
        - os: windows-latest
          arch: ia32
        - os: ubuntu-latest
          arch: armv7l
        # Publishing artifacts for multiple Windows architectures has
        # a bug which can cause the wrong architecture to be downloaded
        # for an update, so until that is fixed, only build Windows x64
        exclude:
        - os: windows-latest
          arch: arm64

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-repo

      - name: Build
        run: pnpm run build
  
      - run: pnpm run publish
        working-directory: ./apps/electron-client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
