name: Publish

on:
  push:
    branches: ["main"]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-repo

      - name: Build
        run: pnpm run build
  
      - run: pnpm run publish
        working-directory: ./apps/electron-client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
